/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paginas;

import com.mycompany.finalp.Daousuariosimp;
import com.mycompany.finalp.Pantalla;
import static com.mycompany.finalp.Pantalla.Showjpanel;
import com.pantalla.interfaces.DAOusuarios;
import com.pantalla.modelos.log;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Isaac
 */
public class Logging extends javax.swing.JPanel {

    /**
     * Creates new form Logging
     */
    public Logging() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Loginform = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Ingresar = new javax.swing.JButton();
        Registrarnuevo = new javax.swing.JButton();
        jPassw = new javax.swing.JPasswordField();
        jing = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        Loginform.setBackground(new java.awt.Color(255, 255, 255));
        Loginform.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 255), 3, true));
        Loginform.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setText("Login");
        Loginform.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 80, 40));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel2.setText("Usuario");
        Loginform.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 130, 30));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel3.setText("Contraseña");
        Loginform.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 220, -1));

        Ingresar.setText("Ingresar");
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        Loginform.add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 190, -1));

        Registrarnuevo.setText("Registrar");
        Registrarnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarnuevoActionPerformed(evt);
            }
        });
        Loginform.add(Registrarnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 108, -1));

        jPassw.setText("jPasswordField1");
        jPassw.setBorder(null);
        Loginform.add(jPassw, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 230, -1));

        jing.setText("Introduce tu usuario");
        jing.setBorder(null);
        jing.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        Loginform.add(jing, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 179, 211, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        Loginform.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 250, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        Loginform.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 240, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(454, Short.MAX_VALUE)
                .addComponent(Loginform, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(285, 285, 285))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Loginform, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarnuevoActionPerformed
Pantalla.Showjpanel(new Registro());
 // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarnuevoActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
 String usuario = jing.getText();
String contrasena = String.valueOf(jPassw.getPassword());

if (usuario.isEmpty() || contrasena.isEmpty()) {
    // Mostrar mensaje de error cuando los campos estén vacíos
    JOptionPane.showMessageDialog(this, "Por favor, ingrese el usuario y la contraseña", "Error", JOptionPane.ERROR_MESSAGE);
    return; // Salir del método si los campos están vacíos
}

try {
    DAOusuarios dao = new Daousuariosimp();
    log usuarioEncontrado = dao.obtenerUsuarioPorUsuarioyContraseña(usuario, contrasena);

    if (usuarioEncontrado != null) {
        // Si se encontró el usuario, mostrar mensaje de éxito
        JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        // Realizar la acción que desees después del inicio de sesión exitoso, por ejemplo, cambiar de pantalla
        Pantalla.Showjpanel(new Mostrarusers());
    } else {
        // Si el usuario no existe o la contraseña es incorrecta, mostrar mensaje de error
        JOptionPane.showMessageDialog(this, "Usuario y/o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
    }
} catch (Exception e) {
    // Mostrar mensaje de error si ocurre una excepción
    JOptionPane.showMessageDialog(this, "Error al intentar iniciar sesión: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}





// TODO add your handling code here:
    }//GEN-LAST:event_IngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ingresar;
    private javax.swing.JPanel Loginform;
    private javax.swing.JButton Registrarnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPassw;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jing;
    // End of variables declaration//GEN-END:variables
}
