/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paginas;

import com.mycompany.finalp.Daousuariosimp;
import static com.mycompany.finalp.Pantalla.Showjpanel;
import com.pantalla.interfaces.DAOusuarios;
import com.pantalla.modelos.log;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Isaac
 */
public class Mostrarusers extends javax.swing.JPanel {

    /**
     * Creates new form mostrar
     */
    public Mostrarusers() {
        initComponents();
        loadusers();
    }

    
    private void loadusers(){
    
    try{
    
    DAOusuarios dao = new Daousuariosimp();
    DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
    
  
    dao.listar().forEach((u)-> model.addRow(new Object[]{u.getNombre(), u.getApellido(), u.getTelefono(), u.getCorreo(), u.getUsuario()}));
    
    }catch(Exception e){
    
    System.out.println(e.getMessage());
    
    }
    
    
    
    
    
    
    
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 255), 2, true));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Telefono ", "Correo", "Usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Cerrar sesion ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(432, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 511, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 Showjpanel(new Logging());       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed

 // Obtener el índice de la fila seleccionada en la tabla
    int rowIndex = jTable1.getSelectedRow();
     DAOusuarios dao = new Daousuariosimp();
    // Verificar si se ha seleccionado una fila
    if (rowIndex == -1) {
        // Si no se ha seleccionado ninguna fila, mostrar un mensaje de error
        JOptionPane.showMessageDialog(this, "Seleccione un usuario para eliminar", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
        // Obtener el valor de la columna "nombre" de la fila seleccionada
        String nombreUsuario = (String) jTable1.getValueAt(rowIndex, 0);
        
        try {
            // Crear una instancia del DAO y llamar al método eliminar con el nombre del usuario
           
            log usuario = new log();
            usuario.setNombre(nombreUsuario);
            dao.eliminar(usuario);
           
            // Actualizar la tabla después de eliminar el registro
            // Eliminar la fila de la tabla a través del modelo
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.removeRow(rowIndex);
           
            // Mostrar un mensaje de éxito
            JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            // Mostrar un mensaje de error si ocurre una excepción
            JOptionPane.showMessageDialog(this, "Error al eliminar el usuario: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
     int rowIndex = jTable1.getSelectedRow();

    if (rowIndex == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un usuario para actualizar", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    } else {
        String nombre = (String) jTable1.getValueAt(rowIndex, 0);
        String apellido = (String) jTable1.getValueAt(rowIndex, 1);
        String telefono = (String) jTable1.getValueAt(rowIndex, 2);
        String correo = (String) jTable1.getValueAt(rowIndex, 3);
        String usuario = (String) jTable1.getValueAt(rowIndex, 4); 
        
        // Crear un objeto log con los datos del usuario seleccionado
        log usuarioSeleccionado = new log();
        usuarioSeleccionado.setNombre(nombre);
        usuarioSeleccionado.setApellido(apellido);
        usuarioSeleccionado.setTelefono(telefono);
        usuarioSeleccionado.setCorreo(correo);
        usuarioSeleccionado.setUsuario(usuario);
        
        // Mostrar el formulario de edición con los datos del usuario seleccionado cargados en él
        Showjpanel(new Registro(usuarioSeleccionado));
    }
      
    



    }//GEN-LAST:event_actualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton actualizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
